name: mindsync
description: "MindSync - Your AI Powered Personal Life Operating System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8


  flutter_markdown_plus: ^1.0.3


  # ==========================
  # State Management
  # ==========================
  provider: ^6.1.5
  flutter_riverpod: ^2.6.1

  # ==========================
  # Navigation
  # ==========================
  go_router: ^16.0.0

  # ==========================
  # Backend
  # ==========================
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^5.1.0

  # ==========================
  # Authentication
  # ==========================
  google_sign_in: ^6.3.0

  # ==========================
  # Fonts & Icons
  # ==========================
  google_fonts: ^6.3.0
  flutter_svg: ^2.2.0

  # ==========================
  # Calendar
  # ==========================
  table_calendar: ^3.2.0

  # ==========================
  # Charts
  # ==========================
  fl_chart: ^1.0.0

  # ==========================
  # Animations
  # ==========================
  lottie: ^3.3.1
  animate_do: ^4.2.0

  # ==========================
  # Glass UI
  # ==========================
  glassmorphism: ^3.0.0

  # ==========================
  # Image Caching
  # ==========================
  cached_network_image: ^3.4.1

  # ==========================
  # Local Notifications
  # ==========================
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1

  # ==========================
  # Internet Connectivity
  # ==========================
  connectivity_plus: ^6.1.4

  # ==========================
  # Utilities
  # ==========================
  intl: ^0.20.2
  uuid: ^4.5.1
  shared_preferences: ^2.5.3

  # ==========================
  # Ai
  # ==========================
  

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/images/logos/

  # Fonts will be added later